### PR TITLE
Update to Vite structure

### PR DESCRIPTION
**Pull request by schrobingus**
robotbuilder is based on Create React App, which is now deprecated and prevents the package from building. This commit updates several packages and converts the package to Vite via [Viject](https://github.com/bhbs/viject). :)

### CODE REVIEW

**Comment by SamCarlberg** [comment]
Thanks for the PR! We'll also want to install a test framework (vitest?) and delete the eject command from package.json to stop referencing the removed `react-scripts` command

https://github.com/wpilibsuite/robotbuilder-2/blob/0d8a3c2e00fb5d63b19db61f13135487cfbfeb0a/package.json#L29-L30

**Comment by BrentBoyMeBob** [comment]
Just replaced with Vitest and it works perfectly, albeit some statements aren't testing the same (replacements will do). I'll send a few examples in a bit.

**Comment by BrentBoyMeBob** [comment]
Sorry for the late response, most tests do work except for the ones provided in CommandGroups.test.jsx, which I'm not sure if it worked before the migration, but the main issue seems to be that a lot of the called DOM elements are mismatching. I'll push my current changes first, and then rewrite that test.

**Comment by BrentBoyMeBob** [comment]
Turns out that toMatchObject is the culprit, as passthroughs seemly refuse to compare, and it has varying levels of sensitivity. Was able to work around the issues by minimizing the newGroup comparison and reimplementing the group2 comparison, and testing is now fully functional. If you have any more suggestions, feel free to let me know as my solution is moreso an organized hack if I'm being honest.

**Comment by SamCarlberg** [comment]
Thanks for keeping this updated! I'll do a full review next week when I'm back at my computer

**Review by SamCarlberg — APPROVED** [review]
Looks good, I'll merge this. Sorry it's taken so long - the FRC season's been taking up practically all of my free time

**Comment by schrobingus** [comment]
All good, I've been quite busy as well. Thanks!

**Pull request merged**
